language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf
      - pdftk
      - imagemagick

# set up an X server to run wkhtmltopdf.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
#  - TESTS="1" ODOO_REPO="OCA/OCB" VERSION="7.0"
  - TESTS="1" ODOO_REPO="OCA/OCB" VERSION="8.0"
#  - TESTS="1" ODOO_REPO="OCA/OCB" VERSION="9.0"
#  - TESTS="1" ODOO_REPO="OCA/OCB" VERSION="10.0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install nose
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
